application: 76-200
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /cv.*
  script: tch/cv/webapp/pages.py
- url: /static
  static_dir: static
  
libraries:
- name: jinja2
  version: latest